name: Cypress Tests

on: push

jobs:
  cypress-run;
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install pnpm
        uses: pnpm/action-setup@4
        with:
          version: 10
          run_install: false

      - name: Install dependencies
        run: pnpm install

      - name: Cypress run
        uses: cypress-io/github-action@v6
        env:
          APP_URL: "http://localhost:3000"
        with:
          build: npm run build
          start: npm start